# Generated by Django 5.0.3 on 2024-06-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_bn',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_es',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='username_bn',
            field=models.CharField(max_length=50, null=True, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='user',
            name='username_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='user',
            name='username_es',
            field=models.CharField(max_length=50, null=True, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='user',
            name='username_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Username'),
        ),
    ]
